github-crawler:

  githubConfig:
    # or if you're using GitHub Enterprise
    # apiUrl: https://your-GHE-instance/api/v3
    apiUrl: https://api.github.com
    organizationName: societe-generale
    oauthToken: "MY_TOKEN_abcdef"

  outputs:
    file:
      filenamePrefix: "SG_repos"