gitHub.url: https://api.github.com

# or if you're using GitHub Enterprise
# gitHub.url: https://your-GHE-instance/api/v3

organizationName: societe-generale

publishExcludedRepositories: false

crawlAllBranches: false

output:
  file:
    filenamePrefix: "SG_repos"


